services:
  bcr-bot:
    build: .
    container_name: bcr-bot
    hostname: bcr-bot
    ports:
      - "2222:22"
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
    restart: unless-stopped
